server:
  port: 8082

spring:
  application:
    name:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
  jmx:
    enabled: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/ms_email?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: MS

  mail:
    host: smtp.gmail.com
    port: 587
    username: wanderson.devjava@gmail.com
    password: jpmypgakzlvhwvlq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
          fallback: false
        ssl:
          enable: true

  rabbitmq:
    addresses:
    queue: ms-queue-email

  logging:
    level:
      liquibase: INFO