version: '2'

services:
  db:
    image: mysql
    command: --default-authetication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
    volumes:
      - ccvn:/var/lib/mysql

volumes:
  ccvn: